### ISSUE TITLE
Re-implement backward compatibility with v1

### ISSUE THREAD

**Issue by mmikeww** [mmikeww/AHKv2-Gdip#11]
Is this possible anymore with the recent v2 changes?

Use this Issue thread to track all ideas and spots that would need to be changed

1. SendMessage return value now returns from the function instead of setting ErrorLevel. What to do? DllCall directly:
https://github.com/Lexikos/AutoHotkey_L/blob/master/source/script2.cpp#L3067

2. Loop can use Helgef's double deref workaround:
https://autohotkey.com/boards/viewtopic.php?p=181697#p181697
```
numLoops := 5
N := (A_AhkVersion < 2) ? numLoops : "numLoops"

Loop %N%
   str .= A_Index " "
```

3. WinGetPos command could use [WinGetPosEx](https://autohotkey.com/boards/viewtopic.php?t=3392) instead. Or just call GetWindowRect directly:
https://github.com/Lexikos/AutoHotkey_L/blob/master/source/script2.cpp#L4072

4. SysGet can be replaced to just do DllCalls directly:
https://github.com/Lexikos/AutoHotkey_L/blob/master/source/script2.cpp#L4161
https://msdn.microsoft.com/en-us/library/windows/desktop/ms724385(v=vs.85).aspx

5. SplitPath should be good as is

6. LoopParse delimiters param will face the string/literal text problem. Could use for-loop and StrSplit?
https://autohotkey.com/boards/viewtopic.php?p=181692#p181692
```
vText := "a,b,c,d,e"
;Loop, Parse, vText, % ","
for k,v in StrSplit(vText, ",")
```

anything else? any other stray commands?

ah fuck, all the Examples use the old GUI syntax

**Comment by mmikeww** [comment]
@nnnik 
@buliasz 
input requested

**Comment by nnnik** [comment]
Why do we need compatability with v2?
The way it looks right now a new person will take over AutoHotkey before Lexikos finishes v2.

**Comment by nnnik** [comment]
SendMessage and PostMessage do have dll Versions too though

**Comment by nnnik** [comment]
For SplitPath you will just have to use RegEx

**Comment by mmikeww** [comment]
@nnnik 
> Why do we need compatability with v2?
> The way it looks right now a new person will take over AutoHotkey before Lexikos finishes v2.

The whole purpose of this library is to add AHK v2 support to the GDIP library. Why are you even using this if not? Go use the normal v1 Gdip_All then

**Comment by nnnik** [comment]
Where could I find it on GitHub?

**Comment by nnnik** [comment]
Hmm yeah I guess I could reimplement it

**Comment by mmikeww** [comment]
@nnnik 
I am first updating the Examples to work with both v1 and v2 but the only way will be to comment and re-comment when switching versions.

If you want to work on the backwards compat that would be good

**Comment by nnnik** [comment]
Yeah if you notify me of updates I wouldn't mind trying to figure a way to keep it compatible with v1

**Comment by mmikeww** [comment]
@nnnik if you want you can start working on items 1-6 at the top

**Comment by nnnik** [comment]
Yeah I will

**Comment by nnnik** [comment]
What about strings?

**Comment by mmikeww** [comment]
What about strings? Can you give an example?

**Comment by nnnik** [comment]
Hmm it seems you don't use '' strings only "" strings.

**Comment by mmikeww** [comment]
i'm working on updating the Examples, here's what it looks like (unfinished):

https://github.com/mmikeww/AHKv2-Gdip/commit/d740b2b3b59b6e8e611a20f6d6e3ed3fa82312fd

**Comment by nnnik** [comment]
I'm almost done with the compatability rewrite
I still need to test it though

**Comment by nnnik** [comment]
@mmikeww I have implemented most of the changes in my fork
[](https://github.com/nnnik/AHKv2-Gdip)

**Comment by mmikeww** [comment]
@nnnik i just pushed the Examples files to this repo. To get the Examples to work on v1 you will need to swap the commented lines. Search for "AHK v1" in each of the Example files. Can you test against them on v1?

**Comment by mmikeww** [comment]
Should be done now. Good work nnnik
